### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by tyrcho** [lbehnke/hierarchical-clustering-java#6]
When I use this with more than 2000 elements, the performance is really slow (16 seconds for 2000, several minutes for 3000). 

It seems the algorithm has a O(n^3) complexity.

The best algorithm (SLINK : http://en.wikipedia.org/wiki/Single-linkage_clustering) for this problem are O(n²).

Any chance you would implement the faster version ?

**Comment by lbehnke** [comment]
When I looked into issue #9 yesterday, I noticed some suspicious code in ClusterPair.agglomerate().
Creating a cluster name that descibes a position in a tree can get *very* expensive when working with many elements. For debugging this is great, but otherwise it is overkill. I'll try to find an alternative naming strategy.

**Comment by barrybecker4** [comment]
@lbehnke, I think that this issue should be reopened. I am seeing the same problem as originally reported by @tyrcho. In fact, running with more than 3000 elements gives an error like:

> An exception or error caused a run to abort: GC overhead limit exceeded 
> java.lang.OutOfMemoryError: GC overhead limit exceeded
> 	at com.apporiented.algorithm.clustering.DistanceMap.hashCodePairNames(DistanceMap.java:107)
> 	at com.apporiented.algorithm.clustering.DistanceMap.hashCodePair(DistanceMap.java:100)

I did some performance tests, and it looks like the times are increasing faster than n^3 as n gets larger. 
In the image below, I bound the actual timing results by n^2 and (n-1)^3 + 3.
<img width="583" alt="h-cluster" src="https://user-images.githubusercontent.com/3020163/52738969-b75c9f80-2f84-11e9-86ee-7f2e491c9afb.PNG">

**Comment by barrybecker4** [comment]
I profiled the code and found that 
99% of the time was being spent in 
`data.remove(remove);`
in DistanceMap.remove(ClusterPair link)
If we simply comment that line out, and not worry about removing items from the priority queue while the agglomeration is happening, things will run _much_ faster. I don't think its that urgent to do the remove because the entire DistanceMap will be reclaimed once the agglomeration is done.
There are still memory issues for large N, but for much larger N than without this change.
Clustering of 2048 nodes took over 16 minutes before this change, but only 10 seconds after.
<img width="344" alt="h-cluster-imp" src="https://user-images.githubusercontent.com/3020163/52757942-4e444e80-2fbb-11e9-9536-5721ddd08567.PNG">

Here are some numbers to show the drastic improvement.
The numbers also seem to indicate approximately N^2 log N runtime performance up until memory issues take over - which is expected.
